<?php
/**
 * Create account form template
 * 
 * @category    design
 * @package     base_default
 * @author      Clarion Magento Team
 */
?>
<?php
/**
 * Create account form template
 *
 * @var $this Mage_Customer_Block_Form_Register
 */
?>
<div class="row">
    <div class="account-create small-10 large-8 colums">
        <div class="page-title">
            <h1><?php echo $this->__('My Account - Register') ?></h1>
        </div>
        <?php echo $this->getChildHtml('form_fields_before')?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.form.register.extra')?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
            <div class="fieldset">
                <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                    </li>
                    <li>
                        <div class="input-box">
                            <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>*" class="input-text validate-email required-entry" />
                        </div>
                    </li>
                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                <?php endif ?>
                <?php if ($this->isNewsletterEnabled()): ?>
                    <li class="control">
                        <div class="checkbox">
                            <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Yes. Keep me up-to-date with kardashian beauty newsletters, special offers and other promotions.') ?>" value="1" id="is_subscribed" checked="checked" class="checkbox" />
                            <label for="is_subscribed"><?php echo $this->__('Yes. Keep me up-to-date with kardashian beauty newsletters, special offers and other promotions.') ?></label>
                        </div>
                        
                        <?php /* Extensions placeholder */ ?>
                        <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                    </li>
                <?php endif ?>
                    <li class="control">
                        <div class="checkbox">
                            <input type="checkbox" name="terms_of_use" value="0" id="terms_of_use" class="checkbox required-entry" />
                            <label for="terms_of_use">By Clicking submit, I agree to the <a href="<?php echo Mage::helper('cms/page')->getPageUrl( 11 ) ?>" target="_blank">Terms of Use</a> and <a href="<?php echo Mage::helper('cms/page')->getPageUrl( 6 ) ?>" target="_blank">Privacy Policy</a> for this website. *</label>
                        </div>
                        
                        <?php /* Extensions placeholder */ ?>
                        <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                    </li>
                </ul>
            </div>
            <!-- custom attributes -->
            <?php $attributeCollection = $this->helper('clarion_customerattribute/customerattribute')->getUserDefinedAttribures(); ?>
            <?php if($attributeCollection->count() > 0) : ?>
                 
                 <!-- For all user defined attributes -->
                 <?php foreach($attributeCollection as $attribute):?>
                    <!-- For all user defined attributes which are set for customer create account -->
                    <?php if($this->helper('clarion_customerattribute/customerattribute')->isAttribureForCustomerAccountCreate($attribute->getAttributeCode())):?>
                 
                        <?php $frontEndLabel = $attribute->getStoreLabel($this->helper('clarion_customerattribute/customerattribute')->getStoreId()); ?>
                        <?php $getAttributeCodeFunction = "get" .  str_replace(' ', '', ucwords(str_replace('_', ' ', $attribute->getAttributeCode()))); ?>
                        <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'required-entry' : '' ?>
                        <?php $fieldFrontendClass = ($attribute->getFrontendClass()) ? $attribute->getFrontendClass() : '' ?>
                        <?php $fieldValue = ($this->getFormData()->$getAttributeCodeFunction()) ? ($this->getFormData()->$getAttributeCodeFunction()) : $attribute->getDefaultValue() ?>
                        <ul class="form-list">
                            <li class="fields">
                               <div class="field">
                                   
                                   <div class="input-box">
                                       
                                       <?php if($attribute->getFrontendInput()== 'text'):?>
                                           <input type="text" name="<?php echo $attribute->getAttributeCode(); ?>" id="<?php echo $attribute->getAttributeCode(); ?>" placeholder="<?php echo $this->__($frontEndLabel) ?><?php if($attribute->getIsRequired()):?>*<?php endif;?>" value="<?php echo $this->escapeHtml($fieldValue); ?>" title="<?php echo $this->__($frontEndLabel); ?>" class="input-text <?php echo $fieldRequiredClass; ?> <?php echo $fieldFrontendClass ;?>" />
                                           
                                       <?php elseif($attribute->getFrontendInput()== 'textarea'):?>
                                           <textarea class=" textarea <?php echo $fieldRequiredClass; ?> <?php echo $fieldFrontendClass ;?>" cols="15" rows="2" placeholder="<?php echo $this->__($frontEndLabel) ?><?php if($attribute->getIsRequired()):?>*<?php endif;?>" title="<?php echo $this->__($frontEndLabel); ?>" name="<?php echo $attribute->getAttributeCode(); ?>" id="<?php echo $attribute->getAttributeCode(); ?>"><?php echo $this->escapeHtml($fieldValue); ?></textarea>
                                         
                                       <?php elseif($attribute->getFrontendInput()== 'date'):?>
                                        <input type="text" style="width:110px !important;" class=" input-text <?php echo $fieldRequiredClass; ?> " placeholder="<?php echo $this->__($frontEndLabel) ?><?php if($attribute->getIsRequired()):?>*<?php endif;?>" title="<?php echo $this->__($frontEndLabel); ?>" value="<?php echo $this->helper('clarion_customerattribute/customerattribute')->getDefaultValueForDate($fieldValue);?>" id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>">
                                        <img style="" title="Select Date" id="<?php echo $attribute->getAttributeCode(); ?>_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/clarion/customerattribute/grid-cal.gif') ?>">
                                            <script type="text/javascript">
                                            //&lt;![CDATA[
                                                Calendar.setup({
                                                    inputField: "<?php echo $attribute->getAttributeCode(); ?>",
                                                    ifFormat: "%m-%d-%Y",
                                                    showsTime: false,
                                                    button: "<?php echo $attribute->getAttributeCode(); ?>_trig",
                                                    align: "Bl",
                                                    singleClick : true
                                                });
                                            //]]&gt;
                                            </script>
                                         
                                        <?php elseif($attribute->getFrontendInput()== 'boolean'):?>
                                        <!-- <div class="checkbox">
                                            <input type="checkbox" name="<?php echo $attribute->getAttributeCode(); ?>" title="<?php echo $this->__($frontEndLabel); ?>" value="0" id="<?php echo $attribute->getAttributeCode(); ?>" class="checkbox" />
                                            <label for="<?php echo $attribute->getAttributeCode(); ?>"><?php echo $this->__($frontEndLabel) ?><?php if($attribute->getIsRequired()):?>class="required"><em>*</em> <?php  else :?>><?php endif;?></label>
                                        </div> -->

                                        <label for="<?php echo $attribute->getAttributeCode(); ?>" <?php if($attribute->getIsRequired()):?>class="required"><em>*</em> <?php  else :?>><?php endif;?><?php echo $this->__($frontEndLabel) ?></label>
                                        <select id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>" title="<?php echo $this->__($frontEndLabel); ?>"<?php if ($attribute->getIsRequired()):?> class="validate-select required-entry "<?php endif; ?>>
                                            <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute($attribute->getAttributeCode())->getSource()->getAllOptions();?>
                                            <option value="">Select</option>
                                            <?php foreach ($options as $option):?>
                                                <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                                            <?php endforeach;?>
                                        </select>
                                            
                                        <?php elseif($attribute->getFrontendInput()== 'select'):?>
                                        <label for="<?php echo $attribute->getAttributeCode(); ?>" <?php if($attribute->getIsRequired()):?>class="required"><em>*</em> <?php  else :?>><?php endif;?><?php echo $this->__($frontEndLabel) ?></label>
                                        <select id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>" title="<?php echo $this->__($frontEndLabel); ?>"<?php if ($attribute->getIsRequired()):?> class="validate-select required-entry "<?php endif; ?>>
                                            <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute($attribute->getAttributeCode())->getSource()->getAllOptions();?>
                                            <?php foreach ($options as $option):?>
                                                <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                                            <?php endforeach;?>
                                        </select>
                                            
                                        <?php elseif($attribute->getFrontendInput()== 'multiselect'):?>
                                        <label for="<?php echo $attribute->getAttributeCode(); ?>" <?php if($attribute->getIsRequired()):?>class="required"><em>*</em> <?php  else :?>><?php endif;?><?php echo $this->__($frontEndLabel) ?></label>
                                        <select multiple="multiple" size="5" id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>[]" title="<?php echo $this->__($frontEndLabel); ?>"  class=" multiselect <?php if ($attribute->getIsRequired()):?> validate-select required-entry<?php endif; ?> ">
                                            <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute($attribute->getAttributeCode())->getSource()->getAllOptions();?>
                                            <?php foreach ($options as $option):?>
                                                <option value="<?php echo $option['value'] ?>"<?php if (in_array($option['value'], explode(',', $fieldValue))) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                                            <?php endforeach;?>
                                        </select>
                                            
                                       <?php endif;?>
                                   </div>
                               </div>
                           </li>
                        </ul>
                  <?php endif;?>
                 <?php endforeach;?>
        <?php endif; ?>
                 
        <?php if($this->getShowAddressFields()): ?>
            <div class="fieldset">
                <input type="hidden" name="create_address" value="1" />
                <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                            </div>
                        </div>
                    </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                <?php endfor; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                    </li>
                </ul>
                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />
            </div>
        <?php endif; ?>
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <div class="input-box">
                                <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>*" class="input-text required-entry validate-password" />
                            </div>
                        </div>
                        <div class="field">
                            <div class="input-box">
                                <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" placeholder="<?php echo $this->__('Confirm Password') ?>*" class="input-text required-entry validate-cpassword" />
                            </div>
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
            </div>
            
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button dark"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('form-validate', true);
            <?php if($this->getShowAddressFields()): ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
            <?php endif; ?>
        //]]>
        </script>
    </div>
</div>